#node'un official image'ini kullanin. versiyon 8

#uygulama 3000 portunu kullaniyor

#node'un uygulamayi yukleyecegimiz dizinine gidecegiz.
#/usr/src/app

#tum dosyalari kopyalayalim

#npm install ile gerekli kutuphaneleri yukleyelim

#son olarak calistiralim
